/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      "on-secondary-container": "#b7b5b4",
      "on-primary-fixed-variant": "#5c4300",
      "surface-container": "#201f1f",
      "surface-variant": "#353534",
      "background": "#131313",
      "secondary-fixed": "#e5e2e1",
      "on-primary-fixed": "#261a00",
      "secondary": "#c8c6c5",
      "on-error-container": "#ffdad6",
      "outline": "#9c8f78",
      "tertiary-container": "#04dcff",
      "outline-variant": "#504532",
      "surface-tint": "#fbbc00",
      "on-tertiary-fixed": "#001f26",
      "surface-dim": "#131313",
      "tertiary-fixed-dim": "#00d9fc",
      "secondary-fixed-dim": "#c8c6c5",
      "on-secondary-fixed": "#1c1b1b",
      "error": "#ffb4ab",
      "inverse-on-surface": "#313030",
      "surface-container-low": "#1c1b1b",
      "primary-container": "#ffbf00",
      "primary-fixed-dim": "#fbbc00",
      "inverse-surface": "#e5e2e1",
      "primary": "#ffe2ab",
      "surface-container-highest": "#353534",
      "on-surface": "#e5e2e1",
      "on-tertiary-fixed-variant": "#004e5c",
      "secondary-container": "#474746",
      "tertiary-fixed": "#aaedff",
      "surface-bright": "#3a3939",
      "error-container": "#93000a",
      "on-primary-container": "#6d5000",
      "surface-container-lowest": "#0e0e0e",
      "on-surface-variant": "#d4c5ab",
      "surface": "#131313",
      "on-tertiary": "#003640",
      "on-secondary": "#313030",
      "tertiary": "#b4efff",
      "on-error": "#690005",
      "primary-fixed": "#ffdfa0",
      "on-tertiary-container": "#005d6d",
      "on-secondary-fixed-variant": "#474746",
      "on-background": "#e5e2e1",
      "inverse-primary": "#795900",
      "on-primary": "#402d00",
      "surface-container-high": "#2a2a2a",
      "transparent": "transparent",
      "white": "#ffffff",
      "black": "#000000",
    },
    fontFamily: {
      "headline": ["Noto Serif"],
      "body": ["Inter"],
      "label": ["Inter"],
      "sans": ["Inter", "system-ui", "sans-serif"],
      "serif": ["Noto Serif", "serif"],
      "mono": ["monospace"],
    },
    borderRadius: {
      "none": "0",
      "DEFAULT": "0.125rem",
      "sm": "0.0625rem",
      "lg": "0.25rem",
      "xl": "0.5rem",
      "full": "0.75rem",
    },
  },
  plugins: [],
}
